### PR TITLE
Read stderr asynchronously to prevent hang if many errors logged

### PR DESCRIPTION
**Pull request by peitschie**
I found this when using inside a docker container that did not contain any of Pango's fonts. The stderr filled up, and the process would hang without terminating.

### CODE REVIEW

**Comment by chtenb** [comment]
Thanks for the report. At which line did you notice the hang? Was it `stdout = memoryStream.ToArray();`?

**Comment by peitschie** [comment]
Hi @chtenb 

I wasn't able to pin down the exact hang point yet.

I'm using this inside a windows docker container, so was not able to attach a debugger easily to find out. After making this change, the process stopped hanging and I could extract the stderr info figure out what was broken. (The windows container lacked any fonts, so the stderr was getting spammed with pango errors)

This is a known issue with streams and processes: https://stackoverflow.com/a/439633

**Comment by chtenb** [comment]
Regardless, this fix makes sense to me. Thanks again!

**Comment by peitschie** [comment]
My pleasure! Thanks for such a useful library. I was despairing of ever finding a straightforward solution to drawing .dot based files until I found your package here. It's saved me loads of time and configuration fiddling!

**Pull request merged**
